version: "3.2"
services:
  php:
    build: 
      context: './phpPHP/'
      args:
       PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
     
  apache:
    build:
      context: './apacheA/'
      args:
       APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
    networks:
      - frontend
      - backend
    ports:
      - "8009:80"
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
     
networks:
  frontend:
  backend:
volumes:
    data:
